CREATE DATABASE LibraryManagerDb;
GO

USE LibraryManagerDb;
GO

CREATE TABLE dbo.Books (
    Id        UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_Books_Id DEFAULT NEWID(),
    Title     NVARCHAR(200) NOT NULL,
    Author    NVARCHAR(200) NOT NULL,
    Genre     NVARCHAR(100) NOT NULL,
    Price     DECIMAL(18, 2) NOT NULL,
    Stock     INT NOT NULL,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Books_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_Books_UpdatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_Books PRIMARY KEY (Id)
);
GO